name: Hello world

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello world!"

  say-hello-inline-python:
    runs-on: ubuntu-latest
    steps:
      - run: print("Hello world!")
        shell: python
